#!/bin/bash

echo "Content-type: text/html"
echo ""

wlan1check=`iwconfig | grep wlan1 | cut -d" " -f1`


if [ $wlan1check = "wlan1" ]; then 
echo "<h2><B>Wi-Fi Adapter is <font color="088A08">Connected</font></B><h2>"
	
else

echo "<B>Wi-Fi Adapter is <font color="red">Not Connected</font></B>"
exit
fi

if [ !  -f /www/cgi-bin/sword/wifi/mon.txt ]; then

echo "<script>alert(\"Wi-Fi monitor mode is not enabled\")</script>"
exit
fi

echo "<html><head><title>WPS Survey </title></head>"
echo "<body>"
echo " " > /www/SWORD/logs/reaver/reaver.txt

wash -i mon1 -s -C > /www/SWORD/logs/reaver/reaver.txt &

/www/cgi-bin/sword/wifi/reaver/refresh

echo "</body></html>"