#!/bin/bash
#echo 0 > /www/cgi-bin/sword/network/sniffer/fc.txt
echo "Content-type: text/html"
echo ""
echo "<html><head><title>WPA Stopped</title></head>"
echo "<body>"
echo "<h2>WPA Survey Stopped.</h2>"
echo "<h3><b>Survey results.</h3>"
echo "<pre>$(killall -9 airodump-ng)</pre>"

#echo "$(pwd)"
cd /www/cgi-bin/sword/wifi/wpa/
#echo "$(pwd)"
echo "<pre>$(cat wpacap-01.csv)</pre>"
echo "</body>"
echo "</html>"
