#!/bin/bash
echo "Content-type: text/html"
echo ""
echo "<H2>WPA Survey Started.</h2>"
#echo "$(pwd)"
cd /www/cgi-bin/sword/wifi/wpa/
#echo "$(pwd)"
rm *.csv
rm *.ivs
echo "<H3>Please wait and enjoy this Gif.</h3"
echo "<br>"
echo "<img src="/SWORD/images/sword.gif">"
airodump-ng -i mon1 --encrypt WPA --output-format csv -w wpacap

echo "</body></html>"



