#!/bin/bash

echo "Content-type: text/html"
echo ""
echo "<html><head><title>WEP Attack Stopped.</title></head>"
echo "<body>"
echo "<h2>WEP Attack Stopped.</h2>"
killall -9 wesside-ng
#killall -9 tail
#ifconfig wlan0 up
echo "<pre>"
#echo "$(cat /www/SWORD/logs/reaver/reaver.txt)"
echo "</pre>"
#cat /www/SWORD/logs/reaver/reaver321.txt
echo "</body>"
echo "</html>"
