#!/bin/bash
echo "Content-type: text/html"
echo ""
echo "<html><head><title>Bash as CGI"
echo "</title></head><body>"
echo "<meta http-equiv="refresh" content="10">"
echo "<h1>Dir</h1>"
cd /www/cgi-bin/sword/wifi/wep

echo "$(airodump-ng mon0 -w peti)"
echo "<pre>$(cat peti-01.csv)</pre>"
echo "</body></html>"

