#!/bin/bash
echo "Content-type: text/html"
echo ""
wlan1check=`iwconfig | grep wlan1 | cut -d" " -f1`


if [ $wlan1check = "wlan1" ]; then 
echo "<h2><B>Wi-Fi Adapter is <font color="088A08">Connected</font></B><h2>"
	
else

echo "<B>Wi-Fi Adapter is <font color="red">Not Connected</font></B>"
exit
fi

if [ !  -f /www/cgi-bin/sword/wifi/mon.txt ]; then

echo "<script>alert(\"Wi-Fi monitor mode is not enabled\")</script>"
exit
fi


echo "<H2> WEP Survey Started.</h2>"
cd /www/cgi-bin/sword/wifi/wep/
rm *.csv
rm *.ivs
echo "<H3>Please wait ...</h3"
echo "<br>"
echo "<br>"
echo "<p align=center><img src="/SWORD/images/sword.gif"></p>"
airodump-ng -i mon1 --encrypt WEP --output-format csv -w wepcap

echo "</body></html>"

#echo "$(pwd)"

#echo "$(pwd)"