#!/bin/bash

echo "Content-type: text/html"
echo ""
echo "<html><head><title>Nmap Port Scan stopped.</title></head>"
echo "<body>"
echo "<h2>Nmap Port Scan stopped..</h2>"
killall -9 nmap
#killall -9 
#ifconfig wlan0 up
echo "<pre>"
#echo "$(cat /www/SWORD/logs/reaver/reaver.txt)"
echo "</pre>"
#cat /www/SWORD/logs/reaver/reaver321.txt
echo "</body>"
echo "</html>"
