#!/bin/ash
echo "Content-type: text/html"
echo ""
echo "<html><head><title>Bash as CGI"
echo "</title></head><body>"

mon0check=`ifconfig | grep mon0 | awk '{print $1}' | cut -b 4`

if [ $mon0check -eq 0 ]; then 

echo "<script>alert(\"Wi-Fi monitor mode already Enabed\")</script>"
echo 1 > /www/cgi-bin/sword/wifi/mon.txt
echo "<h2>iwconfig</h2>"
echo "<pre> $(iwconfig)</pre>"
exit
else
echo "<h2>Starting Monitor Mode on Wlan0</h2>"
echo "<pre> $(airmon-ng start wlan0) </pre>"
echo "<br>"
echo 1 > /www/cgi-bin/sword/wifi/mon.txt
fi

wlan1check=`iwconfig | grep wlan1 | cut -d" " -f1`

if [ $wlan1check = "wlan1" ]; then 
echo "<h2>Wi-Fi Adapter is <font color="088A08">Connected</font></h2>"
echo "<h2>Starting Monitor Mode on Wlan1</h2>"
echo "<pre> $(airmon-ng start wlan1) </pre>"
echo "<br>"
else
#rm /www/cgi-bin/sword/wifi/mon.txt
echo "<B>Wi-Fi Adapter is <font color="red">Not Connected</font></B>"

fi


echo "<h2>iwconfig</h2>"
echo "<pre> $(iwconfig) </pre>"
echo "</body></html>"


