#!/bin/ash
echo "Content-type: text/html"
echo ""
echo "<html><head><title>Bash as CGI"
echo "</title></head><body>"

mon0check=`ifconfig | grep mon0 | awk '{print $1}' | cut -b 4`

if [ $mon0check -eq 0 ]; then 
echo "<h2>Disabling Monitor Mode on mon0</h2>"
echo "<pre> $(airmon-ng stop mon0) </pre>"
rm /www/cgi-bin/sword/wifi/mon.txt

else
echo "<script>alert(\"Wi-Fi monitor mode is not Enabled \")</script>"

#echo "<br>"

echo "<h2>iwconfig</h2>"
echo "<pre>$(iwconfig)</pre>"

exit

fi


wlan1check=`iwconfig | grep wlan1 | cut -d" " -f1`
mon1check=`iwconfig | grep mon1 | cut -d" " -f1`



if [ $wlan1check = "wlan1" ]; then 
echo "<h2>Wi-Fi Adapter is <font color="088A08">Connected</font></h2>"

#elif [ $mon1check = "mon1" ]; then

echo "<h2>Disabling Monitor Mode on mon1</h2>"
echo "<pre> $(airmon-ng stop mon1) </pre>"
echo "<br>"

else
#rm /www/cgi-bin/sword/wifi/mon.txt
echo "<B>Wi-Fi Adapter is <font color="red">Not Connected</font></B>"

fi

echo "<h2>iwconfig</h2>"
echo "<pre> $(iwconfig) </pre>"
echo "</body></html>"

