#!/bin/bash

echo Content-type: text/html
echo ""

if [[ "$QUERY_STRING" =~ "nmap" ]]
#if [[ "nmap" = "nmap" ]]


then
if [[ "$QUERY_STRING" =~ "&nmap" ]]
then
echo "Sh1t detected. Quitting"
exit 1
fi

#ip=`echo "$QUERY_STRING"|cut -d "&" -f1|cut -d "=" -f2`

#cleanip=${ip//[^a-zA-Z0-9.]/}
#cleanip=`echo -n $cleanip | tr A-Z a-z`


a=$(ifconfig | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}' | cut -d. -f1)
b=$(ifconfig | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}' | cut -d. -f2)
c=$(ifconfig | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}' | cut -d. -f3)



#nmap $a.$b.$c.0/24


echo "<h3>Nmap Host Discovery for $a.$b.$c.0/24</h3>"
printf "<pre>\n"
nmap $a.$b.$c.0/24 -T4 -sn
printf "</pre>\n"
#ping -c 4 "$cleanip" 2>&1|sed 's/$/<br>/g'
echo "<hr>"
echo "<p>"
fi

#echo "<form method=get action=\"Nmap\">"
#echo "<input type=text name=nmap>"
#echo "<input type=submit  name=nmap><p>"
#echo "</form>"
